#!/bin/bash

set -vexo pipefail 
mydate="$(date --iso-8601 "seconds")"

# get things up to date

command -v git
command -v uv


if [[ -d .git ]]; then
	git status
fi
uv self version 
if [[ -f .python-version ]]; then
	rm .python-version
fi
if [[ -f .python-versions ]]; then
	rm .python-versions
fi
uv self update
python -VV
uv python install --upgrade
echo "recreate .python-version" 
uv python pin "$(python -V | cut -d " " -f 2)"
cat .python-version 

uv venv --clear
source .venv/bin/activate
python -VV
if [[ ! -f pyproject.toml ]]; then
  uv init
else  
  uv sync 
  cat pyproject.toml 
fi
uv lock --verbose --upgrade 
uv sync --all-extras --dev 
uv --verbose pip install zensical
if [[ -d .git ]]; then
	git status
fi
zensical --version
if [[ ! -f zensical.toml ]]; then
	zensical new
fi
if [[ -d .git ]]; then
	git status
fi
zensical build --clean --strict 

# backup config files
for i in \
	uv.lock \
	.python-version \
	pyproject.toml \
	zensical.toml 
do
	if [[ -f "${i}" ]]; then
	       cp "${i}" "${i}.${mydate}"
	fi
done	

