name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global init.defaultBranch main
      - uses: actions/configure-pages@latest
      - uses: actions/checkout@latest
      - uses: actions/setup-python@latest
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean 
      - uses: actions/upload-pages-artifact@latest
        with:
          path: site
      - uses: actions/deploy-pages@latest
        id: deployment
