name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global init.defaultBranch main
      - uses: actions/configure-pages@latest
      - uses: actions/checkout@latest

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install
        
      - run: uv pip install zensical
      - run: zensical build --clean 
      - uses: actions/upload-pages-artifact@latest
        with:
          path: site
      - uses: actions/deploy-pages@latest
        id: deployment
